feat: navigate to the certificate details from the success screen [WPB-6771]
wireapp/wire-ios-mono pull request #1046
Opened 2024-02-23 17:51 UTC by theswiftway

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Solutions

navigate to the certificate details from the success screen after enrollment

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### How to Test

**Steps**
1. Login to a new client with E2EI enabled
2. Do the enrolment process
3. On the success screen, tap on details button
Expectation: You should see chain of certificates in the details view

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-02-26 15:08 UTC, typfel requested changes

2024-02-26 15:08 UTC, typfel commented on wire-ios-request-strategy/Sources/E2EIdentity/EnrollE2EICertificateUseCase.swift
> +    public func invoke(authenticate: @escaping OAuthBlock) async throws -> String? {
Why is it optional? Don't we throw an error when we fail to generate a certificate?

2024-02-26 15:42 UTC, netbe commented on wire-ios/Wire-iOS Tests/DeviceManagement/MockEnrolE2eICertificateUseCase.swift
>  final class MockEnrolE2eICertificateUseCase: EnrollE2EICertificateUseCaseProtocol {
suggestion: there's a mock in request strategy for it, is it possible to use it in including WireRequestStrategySupport in the tests target?

2024-02-26 15:43 UTC, netbe commented on wire-ios/Wire-iOS/Sources/UserInterface/E2EIdentity/SuccessfulCertificateEnrollmentViewController.swift
> +        let saveFileManger = SaveFileManager(systemFileSavePresenter: SystemSavePresenter())
```suggestion
        let saveFileManager = SaveFileManager(systemFileSavePresenter: SystemSavePresenter())
```

2024-02-26 15:44 UTC, netbe reviewed
added one suggestion, + agree with @typfel on the optional return type

2024-02-27 08:26 UTC, theswiftway commented on wire-ios-request-strategy/Sources/E2EIdentity/EnrollE2EICertificateUseCase.swift
> +    public func invoke(authenticate: @escaping OAuthBlock) async throws -> String? {
done

2024-02-27 08:26 UTC, theswiftway commented on wire-ios/Wire-iOS Tests/DeviceManagement/MockEnrolE2eICertificateUseCase.swift
>  final class MockEnrolE2eICertificateUseCase: EnrollE2EICertificateUseCaseProtocol {
done

2024-02-27 08:26 UTC, theswiftway commented on wire-ios/Wire-iOS/Sources/UserInterface/E2EIdentity/SuccessfulCertificateEnrollmentViewController.swift
> +        let saveFileManger = SaveFileManager(systemFileSavePresenter: SystemSavePresenter())
done

2024-02-27 08:29 UTC, typfel approved these changes

2024-02-27 08:45 UTC, agisilaos approved these changes

2024-02-27 09:04 UTC, merged