feat: Soft lock an app if the certificate has expired WPB-6804
wireapp/wire-ios-mono pull request #1086
Opened 2024-03-05 11:05 UTC by KaterinaWire

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-03-05 15:10 UTC, netbe commented on wire-ios-sync-engine/Source/SessionManager/SessionManager.swift
> +        }
question: do we have to do this on init? or can it be moved to a function and call it explicitly?

2024-03-06 12:32 UTC, typfel requested changes

2024-03-06 12:32 UTC, typfel commented on wire-ios/Wire-iOS/Sources/AppStateCalculator.swift
> +    case pendingCertificateEnroll
```suggestion
    case certificateUpdateRequired
    case certificateEnrollmentRequired
```

2024-03-06 12:32 UTC, typfel commented on wire-ios-sync-engine/Source/SessionManager/SessionManager.swift
> +    func sessionManagerDidUpdateCertificate(for activeSession: UserSession?)
```suggestion
    func sessionManagerRequireCertificateUpdate()
    func sessionManagerRequireCertificateEnrollment()
    func sessionManagerDidUpdateCertificate(for activeSession: UserSession?)
```

2024-03-06 12:32 UTC, typfel commented on wire-ios-sync-engine/Source/SessionManager/SessionManager.swift
> +    private func updateOrEnrollCertificateIfNeeded() async {
```suggestion
    private func requestCertificateUpdateOrEnrollIfNeeded() async {
```

2024-03-06 12:32 UTC, typfel commented on wire-ios-sync-engine/Source/UserSession/ZMUserSession+Certificate.swift
> +    var needsToUpdateCertificate: Bool {
This isn't very testable, can we move this to a `NeedsToUpdateCertificateUseCase`?

2024-03-15 07:54 UTC, typfel approved these changes

2024-03-15 11:02 UTC, David-Henner approved these changes

2024-03-21 15:30 UTC, KaterinaWire commented on wire-ios-sync-engine/Source/SessionManager/SessionManager.swift
> +        }
this was removed

2024-03-21 20:33 UTC, merged