fix(e2ei): clear CRL expiration dates on logout WPB-7148
wireapp/wire-ios-mono pull request #1143
Opened 2024-03-18 14:25 UTC by David-Henner

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

CRL expiration dates are not cleared on logout. If the user logs out and logs back in with the same account, they won't fetch and register the CRLs. This results in being unable to know about revoked certificates until the expiration dates for the CRLs are reached. 

### Solutions

Clear the CRL expiration dates on logout

2024-03-18 14:26 UTC, markusfassbender approved these changes

2024-03-18 14:33 UTC, netbe approved these changes

2024-03-18 14:35 UTC, netbe requested changes
shouldn't we do that before the account is deleted?

2024-03-18 14:36 UTC, netbe commented on wire-ios-sync-engine/Source/SessionManager/SessionManager.swift
> +            self?.clearCRLExpirationDates(for: account)
move this before line 778 in case we delete the account, no?

2024-03-20 14:05 UTC, David-Henner commented on wire-ios-sync-engine/Source/SessionManager/SessionManager.swift
> +            self?.clearCRLExpirationDates(for: account)
done https://github.com/wireapp/wire-ios/pull/1143/commits/6d78fccd7c31dd6f188a3a43ee47224dfab23509

2024-03-20 14:22 UTC, netbe approved these changes

2024-03-20 16:31 UTC, merged