refactor: BackgroundViewController [WPB-8778]
wireapp/wire-ios-mono pull request #1307
Opened 2024-04-18 12:30 UTC by caldrian

<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-8778" title="WPB-8778" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-8778</a>  Clean up code base
  </td></table>
  <br />
 

### Issue

_Please describe the issue._

_Optional: add details about technical approach, solutions etc._

_Optional: reference dependencies to other pull requests etc._

### Testing

_Describe how to test._

_Optional: attachments like images, videos, etc._

---

### Checklist

- [ ] Title contains a reference JIRA issue number like `[WPB-XXX]`.
- [ ] Description is filled and free of optional paragraphs.
- [ ] Adds/updates automated tests.

2024-04-19 18:22 UTC, typfel requested changes

2024-04-19 18:22 UTC, typfel commented on wire-ios/Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
>      private func createBackgroundViewController() {
Maybe delete this function and the assignment directly in `viewDidLoad()`? The name doesn't make sense anymore.

2024-04-22 06:10 UTC, markusfassbender approved these changes
🚮

2024-04-22 08:01 UTC, typfel approved these changes

2024-04-22 08:25 UTC, merged