refactor: remove initial sync observer
wireapp/wire-ios-mono pull request #1563
Opened 2024-06-12 15:07 UTC by markusfassbender

### Issue

_Please describe the issue._

_Optional: add details about technical approach, solutions etc._

_Optional: reference dependencies to other pull requests etc._

### Testing

_Describe how to test._

_Optional: attachments like images, videos, etc._

---

### Checklist

- [ ] Title contains a reference JIRA issue number like `[WPB-XXX]`.
- [ ] Description is filled and free of optional paragraphs.
- [ ] Adds/updates automated tests.

2024-06-12 16:04 UTC, caldrian requested changes

2024-06-12 16:04 UTC, caldrian commented on wire-ios/Wire-iOS/Sources/UserInterface/ConversationList/Container/ViewModel/ConversationListViewControllerViewModel.swift
> +            initialSyncObserverToken = NotificationCenter.default.addObserver(
From the docs:
You must invoke [removeObserver(_:)](https://developer.apple.com/documentation/foundation/notificationcenter/1413994-removeobserver) or [removeObserver(_:name:object:)](https://developer.apple.com/documentation/foundation/notificationcenter/1407263-removeobserver) before the system deallocates any object that [addObserver(forName:object:queue:using:)](https://developer.apple.com/documentation/foundation/notificationcenter/1411723-addobserver) specifies.

In the closure we have a weak `self` reference, however, the `context` is captured.

Also, if we switch accounts, the `notificationContext` is probably deallocated, which violates the API, if I understand correctly ("before the system deallocates any object that addObserver specifies").

Note: if `setupObservers()` is called more than once, the old token is overwritten.

2024-06-12 16:04 UTC, caldrian commented on wire-ios/Wire-iOS/Sources/UserInterface/GroupDetails/GroupDetailsViewController.swift
> +                            self?.initialSyncToken = nil
Same here, `initialSyncToken` must be passed to `removeObserver`.
Setting the property to `nil` is not sufficient.

2024-06-13 07:41 UTC, markusfassbender commented on wire-ios/Wire-iOS/Sources/UserInterface/ConversationList/Container/ViewModel/ConversationListViewControllerViewModel.swift
> +            initialSyncObserverToken = NotificationCenter.default.addObserver(
You are right, thank you! Missed this when switching from `NotificationInContext`, that uses a self unregister token. Reverted some changes, can you please take a look?

2024-06-13 07:57 UTC, caldrian approved these changes

2024-06-13 13:19 UTC, agisilaos approved these changes

2024-06-13 14:01 UTC, merged