fix: Enable `redundant_self_in_closure` & `self_in_property_initialization` - no ticket
wireapp/wire-ios-mono pull request #1675
Opened 2024-07-08 18:44 UTC by agisilaos

This pull request enhances our SwiftLint configuration by enabling two additional rules:

1. `redundant_self_in_closure`: This rule helps identify and prevent unnecessary use of `self` within closures, promoting cleaner and more concise code.

2. `self_in_property_initialization`: This rule encourages explicit use of `self` in property initializers, improving code clarity and reducing potential ambiguity.

Changes made:
- Added `redundant_self_in_closure` to the opt-in rules list
- Added `self_in_property_initialization` to the opt-in rules list

These additions will help maintain consistency across our codebase and align with Swift best practices.

---

### Checklist

- [ ] Title contains a reference JIRA issue number like `[WPB-XXX]`.
- [ ] Description is filled and free of optional paragraphs.
- [ ] Adds/updates automated tests.

2024-07-09 07:10 UTC, markusfassbender approved these changes
Thanks for this cleanup!

2024-07-09 07:10 UTC, markusfassbender commented on wire-ios-sync-engine/Source/SessionManager/APIVersionResolver.swift
>          } else if let apiVersion = commonProductionVersions.max() {
For me the indentation of if and the block are difficult to read for the eye... maybe a blank line can help?

2024-07-09 07:10 UTC, markusfassbender commented on wire-ios-sync-engine/Source/Calling/MLSConferenceStaleParticipantsRemover.swift
> +                        // swiftlint:enable redundant_self_in_closure
These comments are not needed and even create a "superfluous_disable_command" warning.

2024-07-09 07:10 UTC, markusfassbender commented on wire-ios-data-model/Source/Model/Conversation/AssetCollection.swift
> +            // swiftlint:enable redundant_self_in_closure
These comments are not needed and even create a `superfluous_disable_command` warning.

2024-07-09 07:10 UTC, markusfassbender commented on wire-ios-data-model/Source/Model/Conversation/AssetCollectionBatched.swift
> +            // swiftlint:enable redundant_self_in_closure
These comments are not needed and even create a `superfluous_disable_command` warning.

2024-07-09 08:08 UTC, netbe reviewed
I am not convince we need the redundant_self_in_closure rule, maybe we can discuss it

2024-07-09 10:03 UTC, markusfassbender approved these changes

2024-09-20 07:41 UTC, netbe requested changes
remove redundant_self_in_closure or close this PR as it has been stale for a while

2024-09-24 11:11 UTC, agisilaos commented
@netbe I'm closing this in favor of https://github.com/wireapp/wire-ios/pull/1959 Please review.

2024-09-24 11:11 UTC, closed without merging