chore: replace SwiftLint build phase by aggregate target - WPB-8588
wireapp/wire-ios-mono pull request #1687
Opened 2024-07-11 15:34 UTC by caldrian

### Issue

Running SwiftLint increases the build time quite much.
This PR creates an Aggregate target which allows for running SwiftLint manually instead.

### Testing

Open Xcode, choose the "Lint Swift Code" scheme and build.

---

### Checklist

- [x] Title contains a reference JIRA issue number like `[WPB-XXX]`.
- [x] Description is filled and free of optional paragraphs.
- [ ] Adds/updates automated tests.

2024-07-12 07:39 UTC, netbe commented on wire-ios/Wire-iOS.xcodeproj/xcshareddata/xcschemes/Format Swift Code (SwiftFormat).xcscheme
I would suggest to do one aggregated target that lint and format code

2024-07-12 07:39 UTC, netbe requested changes, later dismissed
Let's remove also the precommit swiftlint

2024-07-12 08:25 UTC, markusfassbender approved these changes

2024-07-12 08:25 UTC, markusfassbender commented on .swiftlint.yml
> +swiftlint_version: 0.55.1
This doubles the work @agisilaos  and me did already on some branch recently (I lost track which one). But thanks you updated everything also according to the new rules, we just disabled it 😁

2024-07-15 08:15 UTC, agisilaos approved these changes

2024-07-15 09:35 UTC, netbe approved these changes

2024-07-15 09:35 UTC, merged

2024-07-15 09:53 UTC, samwyndham commented on WireDomain/Sources/WireDomain/Repositories/UpdateEventsRepository.swift
> +            let string = String(decoding: data, as: UTF8.self)
Interesting. Never, seen this initializer before! Will it always succeed to create some kind of string from random data  or does it crash? 

This comment isn't a request to change anything. I'm just interested in this API.

2024-07-15 09:53 UTC, samwyndham commented on wire-ios-link-preview/WireLinkPreview/MetaStreamContainer.swift
> -            ?? String(data: data, encoding: .isoLatin1)
Just a sanity check that it is OK to get rid of `String(data: data, encoding: .isoLatin1)` here?

2024-07-15 09:53 UTC, samwyndham commented on wire-ios-link-preview/WireLinkPreview/MetaStreamContainer.swift
>      private func parseString(from data: Data) -> String? {
I think it is worth making this non optional now for some additional cleanup.