fix: Reset password link - WPB-11566
wireapp/wire-ios-mono pull request #2035
Opened 2024-10-15 16:44 UTC by KaterinaWire

### Issue

The wrong `Reset password` link for C builds.

@netbe I've added the test, but we should make sure that it runs with C builds configurations.

### Testing

Reset password in C builds
---

### Checklist

- [ ] Title contains a reference JIRA issue number like `[WPB-XXX]`.
- [ ] Description is filled and free of optional paragraphs.
- [ ] Adds/updates automated tests.

---

### UI accessibility checklist

_If your PR includes UI changes, please utilize this checklist:_
- [ ] Make sure you use the API for UI elements that support large fonts.
- [ ] All colors are taken from WireDesign.ColorTheme or constructed using WireDesign.BaseColorPalette.
- [ ] New UI elements have Accessibility strings for VoiceOver.

2024-10-15 19:23 UTC, netbe requested changes
there is one step to make it work on C build: we can add it to securitytests plan

2024-10-15 19:23 UTC, netbe commented on wire-ios/Wire-iOS Tests/Bundle/URL+WireTests.swift
> +        XCTAssertEqual(WireURLs.shared.passwordReset, be.accountsURL.appendingPathComponent("forgot"))
1. keep old test and add a new test for this one as test_passwordReset_URLIsCorrect
2. test_passwordReset_URLIsCorrect should be added to the securityTests plan

2024-10-16 08:01 UTC, johnxnguyen approved these changes

2024-10-16 08:04 UTC, netbe approved these changes

2024-10-16 09:01 UTC, merged