chore: adopt API v7 - WPB-12024
wireapp/wire-ios-mono pull request #2247
Opened 2024-12-04 11:02 UTC by caldrian

### Issue

This PR enables version 7 of the api and applies the changes.

### Testing

Test all features of the app against a v7 backend.

---

### Checklist

- [x] Title contains a reference JIRA issue number like `[WPB-XXX]`.
- [x] Description is filled and free of optional paragraphs.
- [x] Adds/updates automated tests.

---

### UI accessibility checklist

_If your PR includes UI changes, please utilize this checklist:_
- [x] Make sure you use the API for UI elements that support large fonts.
- [x] All colors are taken from WireDesign.ColorTheme or constructed using WireDesign.BaseColorPalette.
- [x] New UI elements have Accessibility strings for VoiceOver.

2024-12-04 11:49 UTC, caldrian commented on wire-ios-sync-engine/Tests/Source/Synchronization/Transcoders/UserProfileUpdateRequestStrategyTests.swift
> +            let possibleRequest = sut.nextRequest(for: apiVersion)
I tried to run this test for all API versions, but failed and reverted it.

2024-12-04 11:53 UTC, caldrian commented on WireAPI/Sources/WireAPI/APIs/ConversationsAPI/ConversationsAPIV5.swift
> +        let components = URLComponents(string: "\(oneToOneConversationsPath)/\(domain)/\(userID)")
I wanted to fix this path, but then I had to make all the other changes as well (extending APIVersion etc.).

2024-12-06 08:17 UTC, netbe reviewed
I left a couple of comments.

I wonder also if we need to update the capabilities on WIreAPI for getSelfClient.

2024-12-06 08:17 UTC, netbe commented on WireAPI/Sources/WireAPI/Models/API/APIVersion.swift
> +    public static let productionVersions: Set<Self> = [.v0, .v1, .v2, .v3, .v4, .v5, .v6, .v7]
maybe we should put it in development first then in prod, or is it already finalised?

2024-12-06 08:17 UTC, netbe commented on WireAPI/Sources/WireAPI/APIs/ConversationsAPI/ConversationsAPIV7.swift
> +    override var oneToOneConversationsPath: String {
renamed POST /conversations/one2one → POST /one2one-conversations

renamed GET /conversations/one2one → GET /one2one-conversations

2024-12-06 08:17 UTC, netbe commented on wire-ios-request-strategy/Sources/Request Strategies/MLS/Actions/SyncMLSOneToOneConversationActionHandler.swift
> +        let path = apiVersion >= .v7
renamed GET /conversations/one2one → GET /one2one-conversations

2024-12-06 08:17 UTC, netbe commented on wire-ios-sync-engine/Source/Data Model/ServiceUser.swift
> +        let path = apiVersion >= .v7
renamed POST /conversations/bots → POST /bot/conversations

2024-12-06 08:17 UTC, netbe commented on wire-ios-sync-engine/Source/Synchronization/Strategies/UserProfileUpdateRequestStrategy.swift
> +            let path = apiVersion >= .v7
renamed HEAD /users/handles → HEAD /handles

2024-12-06 08:17 UTC, netbe commented on wire-ios-sync-engine/Source/Synchronization/Strategies/UserProfileUpdateRequestStrategy.swift
> +            let path = apiVersion >= .v7
renamed POST /users/handles → POST /handles

2024-12-06 08:17 UTC, netbe commented on wire-ios-sync-engine/Tests/Source/Synchronization/Transcoders/ZMUserImageTranscoderTests.m
> -    // we'll still assume that the data is the newest. In order to fix that,
unused code ?

2024-12-06 08:17 UTC, netbe commented on wire-ios-transport/Source/Public/APIVersion.swift
> +        self != .v0
nice

2024-12-06 08:42 UTC, caldrian commented on wire-ios-sync-engine/Tests/Source/Synchronization/Transcoders/ZMUserImageTranscoderTests.m
> -    // we'll still assume that the data is the newest. In order to fix that,
Sorry, I should have left a comment.
Yes, this file wasn't referenced in the Xcode project. 
It seems to have been abandoned already before moving to the monorepo.

2024-12-06 08:43 UTC, caldrian commented on WireAPI/Sources/WireAPI/Models/API/APIVersion.swift
> +    public static let productionVersions: Set<Self> = [.v0, .v1, .v2, .v3, .v4, .v5, .v6, .v7]
I'm not sure to be honest. @johnxnguyen do you know the answer?

2024-12-10 08:05 UTC, johnxnguyen requested changes
Looks good, but I would keep version in development until QA runs automation.

2024-12-10 08:05 UTC, johnxnguyen commented on WireAPI/Sources/WireAPI/Models/API/APIVersion.swift
> +    public static let productionVersions: Set<Self> = [.v0, .v1, .v2, .v3, .v4, .v5, .v6, .v7]
the sequence of steps should be:

1. backend freezes api v7
2. client implement v7, but leave it as a development version
3. QA runs full automation with v7 enabled
4. If all checks pass, client moves v7 to production version.

2024-12-10 08:10 UTC, caldrian commented on WireAPI/Sources/WireAPI/Models/API/APIVersion.swift
> +    public static let productionVersions: Set<Self> = [.v0, .v1, .v2, .v3, .v4, .v5, .v6, .v7]
Fixed, thanks! 87c4d034a41c1203255d0e5c322889a0b35a8160

2024-12-10 08:13 UTC, johnxnguyen approved these changes

2024-12-10 12:33 UTC, netbe approved these changes
LGTM :)

2024-12-10 13:44 UTC, merged