feat: add fetchingBackendMLSPublicKeys phase to slow sync - WPB-14361
wireapp/wire-ios-mono pull request #2301
Opened 2024-12-17 08:46 UTC by KaterinaWire

### Issue

### Testing

---

### Checklist

- [ ] Title contains a reference JIRA issue number like `[WPB-XXX]`.
- [ ] Description is filled and free of optional paragraphs.
- [ ] Adds/updates automated tests.

---

### UI accessibility checklist

_If your PR includes UI changes, please utilize this checklist:_
- [ ] Make sure you use the API for UI elements that support large fonts.
- [ ] All colors are taken from WireDesign.ColorTheme or constructed using WireDesign.BaseColorPalette.
- [ ] New UI elements have Accessibility strings for VoiceOver.

2024-12-18 11:12 UTC, johnxnguyen commented on WireAPI/Sources/WireAPI/APIs/BackendInfoAPI/BackendInfoAPIV0.swift
> +class BackendInfoAPIV0: BackendInfoAPI, VersionedAPI {
`/api-version` is a not a versioned endpoint, so it's worth adding a comment now to make it clear that it's not a bug that no version prefix is added.

2024-12-18 11:12 UTC, johnxnguyen commented on WireAPI/Sources/WireAPI/Models/UserClient/MLSPublicKeys.swift
> +        }
Non blocking suggestion:

```suggestion
    func hasValidKey() -> Bool {
        [ed25519, ed448, p256, p384, p512].contains { key in
            guard let key else { return false }
            return !key.isEmpty
        }
```

2024-12-18 11:12 UTC, johnxnguyen commented on WireAPI/Tests/WireAPITests/APIs/BackendInfoAPI/BackendInfoAPITests.swift
> +        try await apiSnapshotHelper.verifyRequest(for: [.v0]) { sut in
I suggest to test all versions to assert that no prefix is added.

2024-12-18 11:12 UTC, johnxnguyen commented on WireAPI/Tests/WireAPITests/APIs/BackendInfoAPI/BackendInfoAPITests.swift
> +        let apiVersions = Set(APIVersion.allCases).subtracting([.v0, .v1, .v2, .v3, .v4])
I think you can write: `.v5.andNextVersions()` or something like that.

2024-12-18 11:12 UTC, johnxnguyen commented on WireDomain/Sources/WireDomain/Repositories/BackendConfig/BackendConfigRepository.swift
> +        storage.set(newValue, forKey: key)
Is this where it's currently stored by the legacy code?

2024-12-18 11:37 UTC, jullianm requested changes
Nice work, left a few comments before approving

2024-12-18 11:37 UTC, jullianm commented on WireAPI/Sources/WireAPI/APIs/BackendInfoAPI/BackendInfoAPIV5.swift
> +private struct BackendMLSPublicKeysResponse: Decodable, ToAPIModelConvertible {
```suggestion
private struct BackendMLSPublicKeysResponseV5: Decodable, ToAPIModelConvertible {
```

2024-12-18 11:37 UTC, jullianm commented on WireAPI/Sources/WireAPI/Models/UserClient/MLSPublicKeys.swift
> +}
I think this is the kind of logic we want to perform at the repository level as we want our API to be solely responsible  of fetching a resource from the backend and provides it to its consumers (the repositories), what do you think?

2024-12-18 11:37 UTC, jullianm commented on WireAPI/Tests/WireAPITests/APIs/BackendInfoAPI/BackendInfoAPITests.swift
> +        let apiVersions = Set(APIVersion.allCases).subtracting([.v0, .v1, .v2, .v3, .v4])
we have a convenience method for that: `APIVersion.v5.andNextVersions`

2024-12-18 11:37 UTC, jullianm commented on WireDomain/Sources/WireDomain/Repositories/BackendConfig/BackendConfigRepository.swift
> +    }
This storage logic should go to a dedicated BackendConfigLocalStore (you can check `UpdateEventsLocalStore` as an example)

2024-12-18 18:10 UTC, KaterinaWire commented on WireAPI/Sources/WireAPI/APIs/BackendInfoAPI/BackendInfoAPIV0.swift
> +class BackendInfoAPIV0: BackendInfoAPI, VersionedAPI {
Added

2024-12-18 18:15 UTC, KaterinaWire commented on WireAPI/Tests/WireAPITests/APIs/BackendInfoAPI/BackendInfoAPITests.swift
> +        try await apiSnapshotHelper.verifyRequest(for: [.v0]) { sut in
done

2024-12-18 18:15 UTC, KaterinaWire commented on WireAPI/Tests/WireAPITests/APIs/BackendInfoAPI/BackendInfoAPITests.swift
> +        let apiVersions = Set(APIVersion.allCases).subtracting([.v0, .v1, .v2, .v3, .v4])
done

2024-12-18 18:16 UTC, KaterinaWire commented on WireAPI/Sources/WireAPI/Models/UserClient/MLSPublicKeys.swift
> +}
Moved to the repository

2024-12-18 18:16 UTC, KaterinaWire commented on WireAPI/Tests/WireAPITests/APIs/BackendInfoAPI/BackendInfoAPITests.swift
> +        let apiVersions = Set(APIVersion.allCases).subtracting([.v0, .v1, .v2, .v3, .v4])
done

2024-12-19 06:05 UTC, KaterinaWire commented on WireDomain/Sources/WireDomain/Repositories/BackendConfig/BackendConfigRepository.swift
> +        storage.set(newValue, forKey: key)
Yes, this is a part of the `BackendInfo`. As @jullianm suggested I've created `BackendConfigLocalStore`, which is likely to be extended. What do you think? @johnxnguyen @jullianm 
Are you going to use `BackendInfo` for new code?

2024-12-19 06:06 UTC, KaterinaWire commented on WireDomain/Sources/WireDomain/Repositories/BackendConfig/BackendConfigRepository.swift
> +    }
Added and replied in the John's comment

2024-12-19 09:08 UTC, jullianm approved these changes
LGTM

2024-12-19 09:14 UTC, jullianm commented on WireDomain/Sources/WireDomain/Repositories/BackendConfig/BackendConfigLocalStore.swift
> +            storage: sharedUserDefaults
this will store the flag with a prefix using the given user ID. I think the MLS enabled flag don't need to be tied to a specific user so you can just use the standard user defaults and remove the `PrivateUserDefaults`

2024-12-19 09:25 UTC, KaterinaWire commented on WireDomain/Sources/WireDomain/Repositories/BackendConfig/BackendConfigLocalStore.swift
> +            storage: sharedUserDefaults
Yes, we don't need it for now. 
Changed

2024-12-23 10:23 UTC, johnxnguyen approved these changes

2024-12-23 10:24 UTC, johnxnguyen commented on WireDomain/Sources/WireDomain/Repositories/BackendConfig/BackendConfigRepository.swift
> +        storage.set(newValue, forKey: key)
If it's the same as what we already have then it's fine but it will change when we support multiple backends.

2024-12-24 08:58 UTC, merged