fix: dismiss to conversations on "Back To Wire" and "Go To Team Management - WPB-15082
wireapp/wire-ios-mono pull request #2305
Opened 2024-12-17 15:51 UTC by El-Fitz

### Issue

When completing the individual to team migration flow, on selecting either "Back To Wire" or "Go To Team Management",  the current modal would be dismissed and, if the user had tapped on "Go To Team Management", the appropriate URL would be opened using the browser.

Instead, when selecting either "Back To Wire" or "Go To Team Management", both the current and the profile's modals should be dismissed (before opening the appropriate browser if the user has tapped on "Go To Team Management").

### Testing

Sign up on staging using a personal account with v7 as the preferred API (when v7 is enabled in staging).
Go through the personal to teams flows.
At the end, tap on "Back To Wire". Both the current and the profile's modals should be dismissed.

Sign up on staging using a personal account with v7 as the preferred API (when v7 is enabled in staging).
Go through the personal to teams flows.
At the end, tap on "Go To Team Management". Both the current and the profile's modals should be dismissed. The team management URL should be opened in your selected browser.

---

### Checklist

- [x] Title contains a reference JIRA issue number like `[WPB-XXX]`.
- [x] Description is filled and free of optional paragraphs.

2024-12-18 08:41 UTC, jullianm approved these changes
LGTM

2024-12-18 16:14 UTC, netbe approved these changes
looks good

2024-12-18 18:08 UTC, El-Fitz commented
Pending feedback on analytics (see `IndividualToTeamMigrationViewController.swift:242`)

2024-12-19 13:19 UTC, El-Fitz commented
The way analytics are currently implemented, `user.personal-team-creation-flow-completed` won't be tracked if the user dismisses the modal in the last step by dragging the view.

2024-12-20 07:51 UTC, netbe requested changes
one character is causing compilation error

2024-12-20 07:51 UTC, netbe commented on WireUI/Sources/WireIndividualToTeamMigrationUI/IndividualToTeamMigrationViewController.swift
> +Í
typo?

2024-12-20 07:51 UTC, netbe commented on WireAnalytics/Sources/WireAnalytics/Events/Predefined/AnalyticsEvent+User.swift
>              }
question: I don't understand the syntax here, what's the closure taking? I thought it was a set of SegmentationEntry

2024-12-20 07:51 UTC, netbe commented on WireUI/Sources/WireIndividualToTeamMigrationUI/IndividualToTeamMigrationViewController.swift
> +Í
typo?

2024-12-20 14:05 UTC, El-Fitz commented on WireAnalytics/Sources/WireAnalytics/Events/Predefined/AnalyticsEvent+User.swift
>              }
It's a Result Builder

2024-12-20 14:06 UTC, netbe approved these changes
LGTM;)

2024-12-20 14:50 UTC, merged