chore: Adding QA automation to iOS repo - WPB-15067
wireapp/wire-ios-mono pull request #2320
Opened 2024-12-20 10:49 UTC by araneforseti

### Issue

To have the tests live with the code they are testing, we are moving the iOS automation tests out of the central QA repo and into the iOS repo

### Testing

Automation running with this branch is viewable in the [New Smoke](https://192.168.2.31/view/iOS/job/iOS-New-Smoke/) job on Jenkins.

It should also be runable locally after going through all the setup

---

### Checklist

- [ ] Title contains a reference JIRA issue number like `[WPB-XXX]`.
- [ ] Description is filled and free of optional paragraphs.
- [ ] Adds/updates automated tests.

---

### UI accessibility checklist

No UI changes

2025-01-06 15:29 UTC, netbe commented on wire-ios-automation/ios/src/main/java/com/wearezeta/auto/ios/common/IOSDriverBuilder.java
> +    };
were all these ids public before? + the list looks outdated
I wonder if it's really needed?

2025-01-06 15:29 UTC, netbe commented on wire-ios-automation/ios/src/main/java/com/wearezeta/auto/ios/common/IOSDriverBuilder.java
> +        processArguments.put("env", ImmutableMap.of("ZMLOG_TAGS", "AVS,calling"));
we should remove this also on our side, ZMLOG is going away, the AVS one has been ported to WireLogger.
"calling" still exists but should soon be ported too

2025-01-06 15:29 UTC, netbe commented on wire-ios-automation/ios/src/main/java/com/wearezeta/auto/ios/common/IOSDriverBuilder.java
> +    };
it could be moved to wire-build-assets if needed

2025-01-07 13:00 UTC, mythsunwind requested changes

2025-01-07 13:00 UTC, mythsunwind commented on wire-ios-automation/ios/.project
.project files are not needed and should be ignored in gitignore

2025-01-07 13:00 UTC, mythsunwind commented on wire-ios-automation/ios/nbactions.xml
Please delete this file. It is a config file for Netbeans. Somebody who used netbeans checked it in accidentially. Maybe add to gitignore too

2025-01-07 13:00 UTC, mythsunwind commented on wire-ios-automation/tools/android/getLatestCand.sh
Please remove

2025-01-07 13:00 UTC, mythsunwind commented on wire-ios-automation/tools/android/getLatestExp.sh
Please remove

2025-01-07 13:00 UTC, mythsunwind commented on wire-ios-automation/tools/android/historian.py
Afaik not used since years. A lot of stuff in the tools folder can be removed.

2025-01-07 13:00 UTC, mythsunwind commented on wire-ios-automation/tools/android_result_aggregator.groovy
Please remove

2025-01-07 13:00 UTC, mythsunwind commented on wire-ios-automation/tools/android/testing-gallery-qa-release.apk
This is some android stuff and can be removed here

2025-01-07 13:00 UTC, mythsunwind commented on wire-ios-automation/tools/img/osx/aqaPictureContact.jpg
It is very likely that all pictures in osx folder are not used by iOS automation. They were from the desktop automation

2025-01-07 13:00 UTC, mythsunwind commented on wire-ios-automation/tools/ios/clickInWindow.py
Please remove

2025-01-07 13:00 UTC, mythsunwind commented on wire-ios-automation/tools/ios/doubleClickInWindow.py
Please remove

2025-01-07 13:00 UTC, mythsunwind commented on wire-ios-automation/tools/ios/misc/project.pbxproj
This is a project file from xcode. Make sure it was not used as example file and delete it.

2025-01-07 13:00 UTC, mythsunwind commented on wire-ios-automation/tools/ios/reconnectIDevice.py
Please remove

2025-01-07 13:00 UTC, mythsunwind commented on wire-ios-automation/tools/ios/simshot
Please remove

2025-01-07 13:00 UTC, mythsunwind commented on wire-ios-automation/tools/ios/swipeInWindow.py
Please remove

2025-01-07 13:00 UTC, mythsunwind commented on wire-ios-automation/tools/ios/zbackuptool
Please remove

2025-01-07 13:00 UTC, mythsunwind commented on wire-ios-automation/tools/timeout
Please remove

2025-01-13 16:13 UTC, mythsunwind commented on wire-ios-automation/tools/img/osx/aqaPictureContact.jpg
you can delete the whole folder for osx

2025-01-13 16:13 UTC, mythsunwind requested changes
I think the whole tools/img/osx directory can be deleted

2025-01-14 12:59 UTC, netbe commented on wire-ios-automation/ios/pom.xml
> +        <deviceName>iPhone 11</deviceName>
I don't know if these credentials are temporary or not, maybe it should not be in clear here

2025-01-14 16:27 UTC, araneforseti commented on wire-ios-automation/ios/pom.xml
> +        <deviceName>iPhone 11</deviceName>
Turns out we don't need it anymore anyways, so removed.

2025-01-15 09:37 UTC, netbe reviewed
Difficult to be exhaustive as the PR is large and not all my field, I've left some comments though

2025-01-15 09:37 UTC, netbe commented on wire-ios-automation/ios/RetrieveIPA.Jenkinsfile.groovy
> +    } else if (track.startsWith("Bund-")) {
this leaks customer name here

2025-01-15 09:37 UTC, netbe commented on wire-ios-automation/ios/Tests.Jenkinsfile.groovy
> +                file(credentialsId: 'KUBECONFIG_bund_next_column_1', variable: 'KUBECONFIG_bund_next_column_1'),
same here

2025-01-15 09:37 UTC, netbe commented on wire-ios-automation/ios/Trigger.Jenkinsfile.groovy
> +      commit_msg = "[${commit_msg}](https://github.com/wireapp/wire-ios-mono/commit/${commit_hash})"
```suggestion
      commit_msg = "[${commit_msg}](https://github.com/wireapp/wire-ios/commit/${commit_hash})"
```

2025-01-15 09:37 UTC, netbe commented on wire-ios-automation/ios/Trigger.Jenkinsfile.groovy
> +      commit_msg = "[${commit_msg}](https://github.com/wireapp/wire-ios-mono/commit/${commit_hash})"
you can replace wire-ios-mono by wire-ios

2025-01-15 09:37 UTC, netbe commented on wire-ios-automation/ios/src/main/java/com/wearezeta/auto/ios/common/IOSDriverBuilder.java
> +        "com.wearezeta.zclient.internal",
can be removed

2025-01-15 09:37 UTC, netbe commented on wire-ios-automation/ios/src/main/java/com/wearezeta/auto/ios/common/IOSDriverBuilder.java
> +        "com.wearezeta.zclient.ios-playground",
does not exist

2025-01-15 09:37 UTC, netbe commented on wire-ios-automation/ios/src/main/java/com/wearezeta/auto/ios/common/Lifecycle.java
> +        driverBuilder.withProcessArgs("--debug-log=Network,SessionManager,event-processing,SyncStatus,OperationStatus,"
I think we need to evaluate in a separate PR these parameters. for reference we should clean up AutomationHelper (https://github.com/wireapp/wire-ios/blob/480e9f2cd7dafb8b0fc6359689f4cff7a2a5293c/wire-ios/WireCommonComponents/AutomationHelper.swift#L113). I've created a ticket to follow up on this: https://wearezeta.atlassian.net/browse/WPB-15403

2025-01-15 09:37 UTC, netbe commented on wire-ios-automation/ios/src/main/java/com/wearezeta/auto/ios/pages/SearchUIPage.java
> +    /**
to delete?

2025-01-15 09:37 UTC, netbe commented on wire-ios-automation/ios/src/main/java/com/wearezeta/auto/ios/pages/TopNavigationBarPage.java
> +//  @iOSXCUITFindBy(accessibility = "Name")
to delete?

2025-01-15 09:37 UTC, netbe commented on wire-ios-automation/ios/src/main/java/com/wearezeta/auto/ios/pages/details_overlay/single/SelfProfilePage.java
> + */
to delete?

2025-01-15 09:37 UTC, netbe commented on wire-ios-automation/ios/src/main/resources/mixpanel.cer
> +-----BEGIN CERTIFICATE-----
question: is it safe to have it here?

2025-01-15 13:17 UTC, araneforseti commented on wire-ios-automation/ios/src/main/java/com/wearezeta/auto/ios/common/Lifecycle.java
> +        driverBuilder.withProcessArgs("--debug-log=Network,SessionManager,event-processing,SyncStatus,OperationStatus,"
Makes sense. I was figuring step 1 was move the code into the iOS repo, then continue the clean up

2025-01-15 13:22 UTC, araneforseti commented on wire-ios-automation/ios/src/main/resources/mixpanel.cer
> +-----BEGIN CERTIFICATE-----
I don't think it's even being used anymore. Removed it

2025-01-15 13:59 UTC, araneforseti commented on wire-ios-automation/ios/RetrieveIPA.Jenkinsfile.groovy
> +    } else if (track.startsWith("Bund-")) {
Removed like the bundle IDs since unneeded if the tests targeting those builds are out of scope for this PR

2025-01-15 14:00 UTC, araneforseti commented
> Difficult to be exhaustive as the PR is large and not all my field, I've left some comments though

Yeah, I'm also getting Sven to review to make sure we get that part covered

2025-01-15 14:08 UTC, mythsunwind approved these changes
LGTM. Let's get this merged 😃

2025-01-15 14:11 UTC, netbe approved these changes

2025-01-15 14:45 UTC, merged