fix: user should not be able to select picture from gallery WPB-90
wireapp/wire-ios-mono pull request #316
Opened 2023-07-04 10:37 UTC by johnranj

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Users should not be able to select picture from library for profile picture

### Solutions

Removed the option to select photos from library.

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-07-04 10:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-ios-mono?pullRequest=316) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-ios-mono?pullRequest=316) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-ios-mono?pullRequest=316) it.</sub>

2023-07-04 12:00 UTC, agisilaos requested changes

2023-07-04 12:00 UTC, agisilaos commented on wire-ios/Wire-iOS/Sources/Managers/Image/ImagePickerManager.swift
> -
@johnranj That removes the ability to `select a picture from the gallery` for everyone. I think there's a check that we do if some features are disabled or not and then apply certain changes to the UI. cc: @KaterinaWire

2023-07-04 14:50 UTC, agisilaos commented on wire-ios/Wire-iOS/Sources/Managers/Image/ImagePickerManager.swift
> -
@johnranj Check MediaShareRestrictionManager class

2023-07-05 18:30 UTC, agisilaos approved these changes

2023-07-06 15:40 UTC, netbe requested changes

2023-07-06 15:40 UTC, netbe commented on wire-ios/Wire-iOS/Sources/Managers/Image/ImagePickerManager.swift
> +
1. Any particular reason for changing the order in the sheet?
2. You're missing the cancel button no?

2023-07-06 15:40 UTC, netbe commented on wire-ios/Wire-iOS/Sources/Managers/Image/ImagePickerManager.swift
> +        guard !MediaShareRestrictionManager(sessionRestriction: ZMUserSession.shared()).isPhotoLibraryEnabled else {
store the class in ImagePickerManager
```
let mediaShareRestrictionManager = MediaShareRestrictionManager(sessionRestriction: ZMUserSession.shared())
```

2023-07-10 08:09 UTC, netbe approved these changes
please cherry-pick to release/cycle-3.110 afterwards

2023-07-11 08:01 UTC, merged