fix problems with internet connection detection SQSERVICES-1917
wireapp/wire-ios-mono pull request #37
Opened 2023-02-21 11:30 UTC by MarcinR

#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability

2023-02-21 11:42 UTC, netbe requested changes
can you add a unit test to it too?

2023-02-21 11:42 UTC, netbe commented on wire-ios-sync-engine/Source/SessionManager/BackendEnvironmentProvider+Reachability.swift
> +                NotificationCenter.default.post(name: NSNotification.Name(rawValue: ZMTransportSessionReachabilityIsEnabled), object: nil)
```suggestion
                NotificationCenter.default.post(name: NSNotification.Name(rawValue: ZMTransportSessionReachabilityIsEnabled), object: self)
```
We could limit to check only the ZMTransportSession that depends on this ReachabilityWrapper renews its observations

2023-02-21 11:42 UTC, netbe commented on wire-ios-transport/Source/TransportSession/ZMTransportSession.m
> +        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(renewReachabilityObserverToken) name:ZMTransportSessionReachabilityIsEnabled object:nil];
```suggestion
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(renewReachabilityObserverToken) name:ZMTransportSessionReachabilityIsEnabled object:self.reachability];
```

2023-02-23 08:41 UTC, netbe approved these changes

2023-02-23 09:03 UTC, KaterinaWire approved these changes

2023-02-23 09:28 UTC, David-Henner approved these changes
Could you please add a description of the issue, the cause, and the solution? It’s helpful for reviewers to understand the context.

2023-02-23 13:23 UTC, merged