fix: increase spacing between reactions WPB-3967
wireapp/wire-ios-mono pull request #421
Opened 2023-08-21 12:50 UTC by lewandowskit93

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Spacing between reactions was to small.

### Solutions

Increased spacing on BasicReactionPicker's stack view and spacings on ReactionsCollectionView.

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-08-21 13:27 UTC, johnxnguyen approved these changes

2023-08-21 13:35 UTC, agisilaos requested changes
@lewandowskit93 The changes broke the UI (at least on iPad) we need to fix that before merging. 

![IMG_0021](https://github.com/wireapp/wire-ios-mono/assets/10944108/d2be03f6-9bd0-406e-a451-e393dc26db73)

2023-08-21 13:58 UTC, MarcinR commented
it looks half empty. I know it wont be as many in one row as in design (screenshot below) but currently it's only 5 in one row and it's not looking good for me. Also  there's not enough space between categories and it looks like one section.
<img width="505" alt="image" src="https://github.com/wireapp/wire-ios-mono/assets/1401672/397c384e-c8c3-41e5-9ace-bff0e758c393">
<img width="393" alt="image" src="https://github.com/wireapp/wire-ios-mono/assets/1401672/95af01d9-7c20-447f-900d-a803246e1141">

2023-08-22 13:11 UTC, agisilaos approved these changes

2023-08-22 16:07 UTC, merged