docs: add README prerequisites for ruby and SSH key
wireapp/wire-ios-mono pull request #639
Opened 2023-11-01 15:46 UTC by markusfassbender

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

On a new machine running `./setup.sh` will produce errors for `gem install bundler`, that you need admin permissions to write to the Apple macOS standard path of ruby.

### Solutions

Therefore to setup the project you need to have `gem` working without admin permissions. This can be archived in multiple ways, so I just added my suggestion to install another ruby version via `rbenv` (can be discussed!).

### Testing

#### Test Coverage (Optional)

- [ ] ~~I have added automated test to this contribution~~

#### How to Test

- install `rbenv` as described in the README

### Notes (Optional)

- Are there other simple ways to get rid of the admin permissions issue?

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-11-01 15:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-ios?pullRequest=639) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-ios?pullRequest=639) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-ios?pullRequest=639) it.</sub>

2023-11-01 16:14 UTC, David-Henner approved these changes

2023-11-02 09:20 UTC, agisilaos approved these changes

2023-11-02 14:08 UTC, netbe commented on README.md
> +- `gem` must be setup to use ruby without admin permissions. One way to archive this is to use [rbenv](https://github.com/rbenv/rbenv), install the latest ruby version and set it as global version.
```suggestion
- `gem` must be setup to use ruby without admin permissions. One way to achieve this is to use [rbenv](https://github.com/rbenv/rbenv), install the latest ruby version and set it as global version.
```

2023-11-02 16:42 UTC, netbe requested changes
just a typo to fix. Also the github check should pass now. Use merge when ready button

2023-11-02 18:01 UTC, netbe approved these changes

2023-11-02 18:04 UTC, merged