feat: Certificate Issuing flow (part 3) WPB-3290
wireapp/wire-ios-mono pull request #738
Opened 2023-11-29 17:30 UTC by KaterinaWire

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

This part contains many steps for certificate enrolling a certificate, including challenges validation. Some of these steps required requests to the Wire server, and I used ApiProvider to access them.
Unfortunately I can't use existing HttpClient to make acme requests and I need to keep `HttpClientE2EI` for now.
----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-11-30 14:49 UTC, David-Henner commented on wire-ios-request-strategy/Sources/E2EIdentity/ACME/AcmeAPITests.swift
> +        let challengeResponseData = try! JSONEncoder.defaultEncoder.encode(expectation)
remove force unwrapping to ensure tests don't crash
```suggestion
        let mockResponse = try XCTUnwrap(HTTPURLResponse(
            url: URL(string: path)!,
            statusCode: 200,
            httpVersion: "",
            headerFields: ["Replay-Nonce": headerNonce]
        ))
        let challengeResponseData = try JSONEncoder.defaultEncoder.encode(expectation)
```

2023-12-01 08:50 UTC, typfel requested changes

2023-12-01 08:50 UTC, typfel commented on wire-ios-request-strategy/Sources/E2EIdentity/EnrollE2eICertificateUseCase.swift
> +            // certificateRequest.response.payloadString()
Delete?

2023-12-01 08:50 UTC, typfel commented on wire-ios-request-strategy/Sources/APIs/E2eIAPI.swift
> +    }
Can you use this helper function?

```suggestion
        mapResponse(response)
    }
```

2023-12-01 08:53 UTC, David-Henner approved these changes

2023-12-01 10:48 UTC, KaterinaWire commented on wire-ios-request-strategy/Sources/E2EIdentity/EnrollE2eICertificateUseCase.swift
> +            // certificateRequest.response.payloadString()
deleted

2023-12-01 10:51 UTC, typfel approved these changes

2023-12-01 14:38 UTC, merged