feat: handle federation errors when adding users to an MLS conversation WPB-2228
wireapp/wire-ios-mono pull request #846
Opened 2024-01-10 16:26 UTC by typfel

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

When adding federated users (or creating a new group) to a conversation, the backends of those users might not be reachable or might not be properly configured to allow the users to be added. If this happens a client should remove exclude these users and insert a system informing the user about the users who couldn't be added.

This logic was already implemented for proteus conversations, this PR enables this logic to also be applied to MLS conversations by parsing and bubbling up federation errors during the MLS add participant action.

### Testing

#### Test Coverage

- [x] I have added automated test to this contribution

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-01-22 15:43 UTC, netbe requested changes
small suggestion + should it target develop now? I thought we merged feat/proteus-to-mls-migration already?

2024-01-22 15:43 UTC, netbe commented on wire-ios-request-strategy/Sources/Request Strategies/MLS/Actions/SendCommitBundleActionHandler.swift
> +
```suggestion
        var unreachableBackends: [String]?
        var nonFederatingBackends: [String]?

        enum CodingKeys: String, CodingKey {
            case unreachableBackends = "unreachable_backends"
            case nonFederatingBackends = "non_federating_backends"
        }
```

2024-01-22 15:45 UTC, typfel commented
> small suggestion + should it target develop now? I thought we merged feat/proteus-to-mls-migration already?

yes it should, I'll update

2024-01-22 15:59 UTC, agisilaos commented
> should it target develop now? I thought we merged feat/proteus-to-mls-migration already?

@typfel @netbe Indeed we merged it to develop but for some reason the branch wasn't deleted.

2024-01-24 09:54 UTC, KaterinaWire commented on wire-ios-request-strategy/Sources/Request Strategies/Conversation/MLSConversationParticipantsService.swift
> +    case failedAddUsers(users: Set<ZMUser>)
Where do we use this error?

2024-01-24 16:26 UTC, David-Henner approved these changes

2024-01-24 16:28 UTC, closed without merging

2024-01-24 16:30 UTC, David-Henner commented
Sorry! didn't mean to close the PR. 
@typfel could you update the target to `develop` ? I think then you'd be able to reopen the PR

2024-01-30 19:27 UTC, typfel commented on wire-ios-request-strategy/Sources/Request Strategies/Conversation/MLSConversationParticipantsService.swift
> +    case failedAddUsers(users: Set<ZMUser>)
Not used, I'll delete