refactor: show username screen on login
wireapp/wire-ios-mono pull request #874
Opened 2024-01-19 10:49 UTC by typfel

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Show a screen for picking a username during the login flow if it's not already set. This previously handled using a takeover screen after the login was completed, that screen has now been removed.

Needs releases with:

- [ ] https://github.com/wireapp/wire-ios/pull/863

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

Invite a new user to team and accept the invitation on the web but don't login in the webapp. Instead login via the iOS app and you will see a username screen after you've entered your credentials.

### Attachments

![D92A1561-565A-45BB-8CFC-F14BDC81B5DB](https://github.com/wireapp/wire-ios/assets/7156/29bad4fb-ffb8-465a-91b7-e673bcbce154)

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-01-24 08:54 UTC, agisilaos requested changes
<img width="341" alt="Screenshot 2024-01-24 at 09 50 25" src="https://github.com/wireapp/wire-ios/assets/10944108/dba91e9f-62b8-4987-96d4-b348b127d7ab">

When logging in and during the login flow we implemented a new button (for accessibility purposes) for logging in/continue to next screen etc. Instead of having this arrow button bound to the textfield. Which isn't accessible. 

More on that button can be found in: `SolidButtonDescription` and how it's implemented in variety of places. 

Can you please replace the arrow button with the solid one? Figma designs can be found [here](https://www.figma.com/file/exxrpYZ28N1WOylyw9TYh1/Accessibility-Quick-Wins-(iOS)?type=design&node-id=402-3707&mode=design&t=I5wE32ugiHeqOQJS-0)

2024-01-26 11:28 UTC, David-Henner approved these changes

2024-01-26 14:47 UTC, typfel commented
> <img alt="Screenshot 2024-01-24 at 09 50 25" width="341" src="https://private-user-images.githubusercontent.com/10944108/299250612-dba91e9f-62b8-4987-96d4-b348b127d7ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODAyNTMsIm5iZiI6MTcwNjI3OTk1MywicGF0aCI6Ii8xMDk0NDEwOC8yOTkyNTA2MTItZGJhOTFlOWYtNjJiOC00OTg3LTk2ZDQtYjM0OGIxMjdkN2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE0MzkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MzNhYzBlZDUyM2NiNzQzYWVjNTAyNDdhYTM0YWVjYWE3ZmY2YzUzYTQ2NDYzMWI2NzMzYjIwZWZmZDUzYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R82MT3h8oJwOhezJ46ANLaUH3P-W7dDlhscWAGzizlI">
> When logging in and during the login flow we implemented a new button (for accessibility purposes) for logging in/continue to next screen etc. Instead of having this arrow button bound to the textfield. Which isn't accessible.
> 
> More on that button can be found in: `SolidButtonDescription` and how it's implemented in variety of places.
> 
> Can you please replace the arrow button with the solid one? Figma designs can be found [here](https://www.figma.com/file/exxrpYZ28N1WOylyw9TYh1/Accessibility-Quick-Wins-(iOS)?type=design&node-id=402-3707&mode=design&t=I5wE32ugiHeqOQJS-0)

Ok, I looked into what takes to achieve and I would need to do some big refactoring of the `AuthenticationStepController` and the `ValidatedTextField` to support an external confirm button since as it is now there's no building blocks to achieve this without writing a completely custom view controller for this screen.

I created separate ticket for this: https://wearezeta.atlassian.net/browse/WPB-6292

2024-01-26 14:51 UTC, agisilaos approved these changes
Looking good!

2024-01-26 14:51 UTC, agisilaos commented on wire-ios-sync-engine/Source/Data Model/ZMUser+Consent.swift
> +        request.add(ZMCompletionHandler(on: context ) { response in
```suggestion
        request.add(ZMCompletionHandler(on: context) { response in
```

2024-01-26 19:57 UTC, merged